name: JSDoc
on: push

jobs:
  jsdoc:
    name: JSDoc
    runs-on: ubuntu-latest
    steps:
      - name: npm ci
        run: npm ci
      - name: Build JSDoc
        run: npm run doc
        with:
          node-version: '12.x'